services:
  web:
    build:
      context: ./my-app  # Path to your Next.js app
      dockerfile: Dockerfile   # Specify Dockerfile name if different
    ports:
      - "3000:3000"            # Expose Next.js app on port 3000
    environment:
      - MONGO_URI=mongodb://mongo:27017/pii_database  # MongoDB connection string

  backend:
    build:
      context: ./backend       # Path to your FastAPI app
      dockerfile: Dockerfile   # Specify Dockerfile name if different
    ports:
      - "8000:8000"            # Expose FastAPI app on port 8000
    depends_on:
      - mongo                   # Ensure MongoDB is started before the backend

  mongo:
    build:
      context: ./mongo   # Path to your MongoDB Dockerfile folder
      dockerfile: Dockerfile     # Specify Dockerfile name if different
    ports:
      - "27017:27017"            # Expose MongoDB on port 27017
    volumes:
      - mongo-data:/data/db      # Persist MongoDB data

volumes:
  mongo-data:                    # Define a volume for MongoDB data persistence